version: "3.9"
services:
  weba:
    build: ./nginx
    expose:
      - "80"
  
  webb:
    build: ./nginx
    expose:
      - "80"

  haproxy:
    build: ./haproxy
    links:
      - weba
      - webb
    ports:
      - "80:80"
      - "70:70"
    expose:
      - "80"
      - "70"