version: "3.9"

networks:
  backend:

services:
  weba:
    build: ./nginx
    expose:
      - "80"
    networks:
      - backend
  
  webb:
    build: ./nginx
    expose:
      - "80"
    networks:
      - backend

  webc:
    build: ./nginx
    expose:
      - "80"
    networks:
      - backend
      
  haproxy:
    build: ./haproxy
    networks: 
      - backend
    ports:
      - "80:80"
